//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistrationSystem
{


    public partial class Setup
    {

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// txtServerName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtServerName;

        /// <summary>
        /// ddlAuth control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlAuth;

        /// <summary>
        /// txtUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtUsername;

        /// <summary>
        /// txtPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        /// <summary>
        /// btnTestConnection control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnTestConnection;

        /// <summary>
        /// lblConnectionStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblConnectionStatus;

        /// <summary>
        /// btnCreateDatabase control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCreateDatabase;

        /// <summary>
        /// lblDatabaseStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblDatabaseStatus;

        /// <summary>
        /// btnCreateStoredProcedures control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCreateStoredProcedures;

        /// <summary>
        /// lblStoredProcStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStoredProcStatus;

        /// <summary>
        /// hlHome control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink hlHome;
    }
}
